// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7oZ3xskDeXH3S0pjlcKg-bG3AwbsiKVY',
    appId: '1:652255037282:web:5eddc44a491c67ba470e3b',
    messagingSenderId: '652255037282',
    projectId: 'vehicles-a5db1',
    authDomain: 'vehicles-a5db1.firebaseapp.com',
    storageBucket: 'vehicles-a5db1.firebasestorage.app',
    measurementId: 'G-JVQ4JQPR07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCIl_nnhsUWFoRo5mzShbl18Ae_fwI6Cg',
    appId: '1:652255037282:android:da7f72a355708282470e3b',
    messagingSenderId: '652255037282',
    projectId: 'vehicles-a5db1',
    storageBucket: 'vehicles-a5db1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlRfcDsJhvdn2FS6O92G8Suwwh6xo4q3A',
    appId: '1:652255037282:ios:5027a144227d6e3b470e3b',
    messagingSenderId: '652255037282',
    projectId: 'vehicles-a5db1',
    storageBucket: 'vehicles-a5db1.firebasestorage.app',
    iosBundleId: 'com.example.vehicles',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlRfcDsJhvdn2FS6O92G8Suwwh6xo4q3A',
    appId: '1:652255037282:ios:5027a144227d6e3b470e3b',
    messagingSenderId: '652255037282',
    projectId: 'vehicles-a5db1',
    storageBucket: 'vehicles-a5db1.firebasestorage.app',
    iosBundleId: 'com.example.vehicles',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7oZ3xskDeXH3S0pjlcKg-bG3AwbsiKVY',
    appId: '1:652255037282:web:95a416ab3a00346c470e3b',
    messagingSenderId: '652255037282',
    projectId: 'vehicles-a5db1',
    authDomain: 'vehicles-a5db1.firebaseapp.com',
    storageBucket: 'vehicles-a5db1.firebasestorage.app',
    measurementId: 'G-T3KLBGTL7S',
  );

}